dist: bionic

sudo: required

language: shell

services: 
  - docker

env:
 global:
   - CENTOS_VERSION=7.8.2003
   - DOCKER_VERSION=19.03.12-3
   - DOCKER_TAG=v1.0

before_install:
  - sudo apt-get -y install createrepo
  - docker pull centos:${CENTOS_VERSION}
   
install: 
>-
  docker run -t --rm -v /tmp/rpms:/rpms centos:${CENTOS_VERSION}
  bash -c
  "yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
   && yum install -y centos-release-openstack-train \
   && curl -o /etc/yum.repos.d/docker-ce.repo https://download.docker.com/linux/centos/docker-ce.repo \
   && mkdir -p /rpms/ \
   && yum install -y --downloadonly --downloaddir=/rpms docker-ce-${DOCKER_VERSION}.el7.x86_64 docker-ce-cli-${DOCKER_VERSION}.el7.x86_64 docker-compose \
   && yum install -y --downloadonly --downloaddir=/rpms vim wget chrony rsync jq git tcpdump nc net-tools perl unzip \
   && yum install -y --downloadonly --downloaddir=/rpms python-pip python-devel libffi-devel gcc openssl-devel libselinux-python ansible \
   && yum install -y --downloadonly --downloaddir=/rpms centos-release-openstack-train python-openstackclient openstack-selinux \
   && yum install -y --downloadonly --downloaddir=/rpms createrepo"

before_script:
  - ls -l /tmp/
  - ls -l /tmp/rpms
  - sudo chmod -R 766 /tmp/rpms
  - ls -l /tmp/rpms
  - createrepo /tmp/rpms
  - docker build -t willdockerhub/yum-repo:$DOCKER_TAG .

script:
  - docker-compose up -d
  - docker-compose ps
  - docker exec -it yum-repo-client yum install -y docker-ce

after_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push willdockerhub/yum-repo:$DOCKER_TAG
