sudo: required

services:
- docker

env:
 global:
   - CENTOS_VERSION=7.8.2003
   - DOCKER_VERSION=19.03.12-3
   - DOCKER_TAG=v1.0

before_install:
- docker pull centos:${CENTOS_VERSION}
- while sleep 5m; do echo "=====[ $SECONDS seconds, still building... ]====="; done &
   
script:
- >
  docker run -t --rm -v ${PWD}/rpms:/rpms centos:${CENTOS_VERSION}
  bash -c
  "yum install -y reposync createrepo &&
   yum install -y centos-release-openstack-train &&
   mkdir -p /rpms/ &&
   reposync -p /rpms &&
   for file in $(ls /rpms);do createrepo /rpms/$file;done"
  
- sudo chmod -R 755 ${PWD}/rpms
- docker build -t willdockerhub/yum-repo:$DOCKER_TAG .
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push willdockerhub/yum-repo:$DOCKER_TAG
