sudo: required

services:
- docker

env:
 global:
   - CENTOS_VERSION=7.8.2003
   # yum list docker-ce --showduplicates
   - DOCKER_VERSION=19.03.12-3
   - DOCKER_TAG=v1.0

before_install:
- docker pull centos:${CENTOS_VERSION}
   

script:
- >
  docker run -t --rm -v ${PWD}/rpms:/rpms centos:${CENTOS_VERSION}
  bash -c
  "yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm &&
   curl -o /etc/yum.repos.d/docker-ce.repo https://download.docker.com/linux/centos/docker-ce.repo &&
   mkdir -p /rpms/ &&
   yum install -y $(cat requirement.txt) &&
   yum clean all &&
   createrepo /rpms"
  
- sudo chmod -R 755 ${PWD}/rpms
- docker build -t willdockerhub/yum-repo:$DOCKER_TAG .
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push willdockerhub/yum-repo:$DOCKER_TAG
